image: node:20

stages:
  - quality

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - corepack enable
  - yarn install --immutable

lint:
  stage: quality
  script:
    - yarn lint

typecheck:
  stage: quality
  script:
    - npx tsc --noEmit

test:
  stage: quality
  script:
    - yarn test --passWithNoTests

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH == "main"'
